#!/usr/bin/env pwsh

Write-Output "Lint and Test before push..."

Invoke-Command -ScriptBlock {./gradlew check lintKotlin editorConfigCheck allTests} | Out-Null
if($LASTEXITCODE -ne 0) {
    Write-Output "pre-push checks failed"
    EXIT 1
}